# Generated by Django 5.1.3 on 2025-11-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_credits',
        ),
        migrations.AlterField(
            model_name='offer',
            name='time_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='available_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='blocked_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='total_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timebank', to='rest_api.user'),
        ),
        migrations.AlterField(
            model_name='want',
            name='time_offered',
            field=models.IntegerField(default=1),
        ),
    ]
