# Generated by Django 5.1.3 on 2025-11-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_userprofile_time_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='want',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='videos',
        ),
        migrations.AddField(
            model_name='exchange',
            name='offer_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'offer_type': 'want'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_2', to='rest_api.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='activity_type',
            field=models.CharField(choices=[('1to1', '1 to 1'), ('group', 'Group')], default='1to1', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='location_type',
            field=models.CharField(choices=[('myLocation', 'My Location'), ('otherLocation', 'Remote')], default='myLocation', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('1time', '1 time'), ('recurring', 'Recurring')], default='1time', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='person_count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Want',
        ),
    ]
