# Generated by Django 5.1.3 on 2025-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_remove_exchange_want_remove_offer_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='geo_location',
            field=models.JSONField(default=list),
        ),
    ]
