# Generated by Django 5.1.3 on 2025-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_offer_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='geo_location',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
