# Generated by Django 5.1.3 on 2025-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_offer_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='time',
        ),
        migrations.AddField(
            model_name='offer',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='person_count',
            field=models.IntegerField(default=1),
        ),
    ]
