# Generated by Django 5.1.3 on 2025-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_offer_date_remove_offer_time_offer_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
