# Generated by Django 5.1.3 on 2025-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_offer_date_offer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('offer', 'Offer'), ('want', 'Want')], default='offer', max_length=20),
        ),
    ]
