# Generated by Django 5.1.3 on 2025-12-02 12:16

import django.db.models.deletion
import rest_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='offer_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'want'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_2', to='rest_api.offer'),
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rest_api.models.offer_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_images', to='rest_api.offer')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
