# Generated by Django 5.1.3 on 2025-12-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_exchange_offer_2_offerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='provider_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='requester_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExchangeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('would_recommend', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rest_api.exchange')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='rest_api.user')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='rest_api.user')),
            ],
            options={
                'unique_together': {('exchange', 'rater', 'ratee')},
            },
        ),
    ]
