# Generated by Django 5.2.7 on 2025-12-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_exchange_proposed_date_exchange_proposed_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('offer', 'Offer'), ('want', 'Want'), ('exchange', 'Exchange'), ('user', 'User')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate Content'), ('FAKE_PROFILE', 'Fake Profile'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Fraud'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='rest_api.user')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to='rest_api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
