# Generated by Django 5.2.7 on 2025-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_report_reported_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
