# Generated by Django 5.2.7 on 2025-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_add_is_read_to_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='offer_2',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Handshake',
        ),
    ]
