# Generated by Django 5.2.7 on 2025-12-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_remove_handshake_and_offer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
    ]
