# Generated by Django 5.2.7 on 2025-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_remove_achievements_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='provider_paid',
            field=models.BooleanField(default=False),
        ),
    ]
