# Generated by Django 5.2.7 on 2025-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_add_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='location_type',
            field=models.CharField(choices=[('myLocation', 'My Location'), ('remote', 'Remote')], default='myLocation', max_length=20),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='amount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='available_amount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='total_amount',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
