# Generated by Django 5.2.7 on 2025-12-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_alter_offer_location_type_alter_timebank_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='flagged_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
