# Generated by Django 5.2.7 on 2025-12-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_offer_flagged_reason_offer_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
