# Generated by data migration for timezone-aware datetime fields

from django.db import migrations
from django.utils import timezone
from datetime import datetime


def migrate_offer_datetime(apps, schema_editor):
    """Migrate existing date+time fields to scheduled_at"""
    Offer = apps.get_model('rest_api', 'Offer')
    
    for offer in Offer.objects.filter(date__isnull=False, scheduled_at__isnull=True):
        if offer.time:
            naive_dt = datetime.combine(offer.date, offer.time)
        else:
            naive_dt = datetime.combine(offer.date, datetime.min.time())
        
        # Make timezone-aware using Django's default timezone
        offer.scheduled_at = timezone.make_aware(naive_dt, timezone.get_current_timezone())
        offer.save(update_fields=['scheduled_at'])


def migrate_exchange_datetime(apps, schema_editor):
    """Migrate existing proposed_date+proposed_time fields to proposed_at"""
    Exchange = apps.get_model('rest_api', 'Exchange')
    
    for exchange in Exchange.objects.filter(proposed_date__isnull=False, proposed_at__isnull=True):
        if exchange.proposed_time:
            naive_dt = datetime.combine(exchange.proposed_date, exchange.proposed_time)
        else:
            naive_dt = datetime.combine(exchange.proposed_date, datetime.min.time())
        
        # Make timezone-aware using Django's default timezone
        exchange.proposed_at = timezone.make_aware(naive_dt, timezone.get_current_timezone())
        exchange.save(update_fields=['proposed_at'])


def reverse_migration(apps, schema_editor):
    """No-op reverse migration - legacy fields are preserved"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_add_timezone_aware_datetime_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_offer_datetime, reverse_migration),
        migrations.RunPython(migrate_exchange_datetime, reverse_migration),
    ]

