# Generated by Django 5.2.7 on 2025-12-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_migrate_legacy_datetime_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='proposed_date',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='proposed_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='time',
        ),
    ]
